// <auto-generated />
namespace RapidRecipeRecall.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FKinNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKinNote));
        
        string IMigrationMetadata.Id
        {
            get { return "202009151742282_FKinNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
